// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHC3WT8zxrj6CJ1Up41-o_DYr4ehmFfxg',
    appId: '1:523166610417:web:20dc4af191c5e261b34a50',
    messagingSenderId: '523166610417',
    projectId: 'excercise-apps-4df93',
    authDomain: 'excercise-apps-4df93.firebaseapp.com',
    storageBucket: 'excercise-apps-4df93.firebasestorage.app',
    measurementId: 'G-HLH9WJCJ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3psodV0WdZaOt-8pe2U8jvr24cowGy4',
    appId: '1:523166610417:android:43810f2ba0903d66b34a50',
    messagingSenderId: '523166610417',
    projectId: 'excercise-apps-4df93',
    storageBucket: 'excercise-apps-4df93.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHC3WT8zxrj6CJ1Up41-o_DYr4ehmFfxg',
    appId: '1:523166610417:web:5e86eb1e8ad7f53fb34a50',
    messagingSenderId: '523166610417',
    projectId: 'excercise-apps-4df93',
    authDomain: 'excercise-apps-4df93.firebaseapp.com',
    storageBucket: 'excercise-apps-4df93.firebasestorage.app',
    measurementId: 'G-7TB6FMFB7Y',
  );
}
